language: cpp
dist: bionic

# Install LLVM
addons:
  apt:
    update: true
    sources:
      - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-13 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - llvm-13
      - llvm-13-dev
      - llvm-13-tools
      - clang-13
      - libclang-common-13-dev
      - libclang-13-dev
      - python3
      - python3-pip

env:
  - CONFIGURATION=Debug
  - CONFIGURATION=Release

compiler:
  - clang
  - gcc

# AFAIK, there's no other way of obtaining LLVM's lit other than via `pip
# install`
install:
  - pip3 install --user lit

script:
  # The latest version of CMake available in Travis is 3.13.4. That's
  # insufficient for LLVM and llvm-tutor. Download more recent version and use
  # that instead.
  - CMAKE_DIR="/home/travis/build/banach-space/cmake/"
  - mkdir $CMAKE_DIR && cd $CMAKE_DIR
  - wget https://github.com/Kitware/CMake/releases/download/v3.21.3/cmake-3.21.3-linux-x86_64.sh
  - checksum=7b7052b09afb059dd64673ee4fedff0e7f6067e9f4adb76e23f09e6e9a304931
  - echo "$checksum cmake-3.21.3-linux-x86_64.sh" | sha256sum -c -
  - bash cmake-3.21.3-linux-x86_64.sh --skip-license
  # Build HelloWorld as a standalone project
  - cd $HOME/build/banach-space/clang-tutor/HelloWorld
  - mkdir build && cd build
  - $CMAKE_DIR/bin/cmake -DCT_LLVM_INSTALL_DIR=/usr/lib/llvm-13/ -DCMAKE_BUILD_TYPE=$CONFIGURATION ../
  - make -j4
  # Build the top project and run tests
  - cd ../../
  - mkdir build
  - cd build
  - $CMAKE_DIR/bin/cmake -DCT_LLVM_INSTALL_DIR=/usr/lib/llvm-13/ -DCMAKE_BUILD_TYPE=$CONFIGURATION ../
  - make -j4
  - lit test/
